// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "apiToken": string;
      "spaceId": string;
      "autoSync": boolean;
      "syncOnItemChange": boolean;
      "includePageNumbers": boolean;
      "includeTags": boolean;
      "useColorEmoji": boolean;
      "processedItems": string;
    };
  }
}
